laravel/app/routes.php
<?php

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('empresa/{slug?}', array('as' => 'empresa', 'uses' => 'EmpresaController@index'));
Route::get('produtos', array('as' => 'produtos', 'uses' => 'ProdutosController@index'));
Route::get('produtos/{categoria}/{produto}', array('as' => 'produtos.detalhes', 'uses' => 'ProdutosController@detalhes'));
Route::get('cases', array('as' => 'cases', 'uses' => 'CasesController@index'));
Route::get('cases/detalhes/{slug}', array('as' => 'cases.detalhes', 'uses' => 'CasesController@detalhes'));
Route::get('clientes', array('as' => 'clientes', 'uses' => 'ClientesController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('contato/enviar', 'ContatoController@enviar');
Route::post('contato/trabalhe', 'ContatoController@trabalhe');

Route::get('espaco-do-arquiteto', array('as' => 'espaco', 'uses' => 'EspacoController@index'));
Route::post('espaco-do-arquiteto', array('as' => 'espaco.login', 'uses' => 'EspacoController@login'));
Route::post('cadastro-do-arquiteto', array('as' => 'espaco.cadastro', 'uses' => 'EspacoController@cadastro'));
Route::get('espaco-do-arquiteto/categoria/{slug}', array('as' => 'espaco.categoria', 'uses' => 'EspacoController@categoria'));
Route::get('espaco-do-arquiteto/logout', array('as' => 'espaco.logout', function(){
	Auth::arquiteto()->logout();
	return Redirect::to('espaco-do-arquiteto');
}));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));


Route::get('download/{arquivo?}', array('before' => 'auth.espaco', function($arquivo){
	
	$pathToFile = app_path() . '/internal_files/'.$arquivo;
	
	if(!$arquivo || !file_exists($pathToFile)){
		App::abort('404');
	}else{
		
		\EspacoUsuario::where('id', '=', Auth::arquiteto()->get()->id)->first()
							   										  ->downloads()
							   										  ->attach(\EspacoArquivo::where('arquivo', '=', $arquivo)->first()->id, array('created_at' => date('Y-m-d H:i:s')));
	
		return Response::download($pathToFile);
	}
}));

Route::get('downloadadmin/{arquivo?}', array('before' => 'painel.auth', function($arquivo){
	
	$pathToFile = app_path() . '/internal_files/'.$arquivo;
	
	if(!$arquivo || !file_exists($pathToFile)){
		App::abort('404');
	}else{
		return Response::download($pathToFile);
	}
}));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'login' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::admin()->attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::admin()->logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));
Route::post('ajax/buscarSubcategorias', array('before' => 'auth', 'uses' => 'Painel\AjaxController@buscarSubcategorias'));
Route::post('ajax/gravarRelAcabamento', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravarRelAcabamento'));
Route::post('ajax/adicionarCadastroNewsletter', 'Painel\AjaxController@adicionarCadastroNewsletter');
Route::get('ajax/buscarAcabamentos/{id_produto}', array('before' => 'auth', 'uses' => 'Painel\AjaxController@buscarAcabamentos'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('texto-da-home', 'Painel\TextoHomeController');
	Route::resource('chamadas', 'Painel\ChamadasController');
	Route::resource('empresa', 'Painel\EmpresaController');
	Route::resource('clientes', 'Painel\ClientesController');
	Route::resource('clientesbanner', 'Painel\ClientesBannerController');	
	Route::resource('contato', 'Painel\ContatoController');
	Route::resource('cases', 'Painel\CasesController');
	Route::resource('casesimagens', 'Painel\CasesImagensController');
	Route::resource('cadastros', 'Painel\CadastrosController', array('only' => array('index', 'destroy')));
	Route::resource('produtoscategorias', 'Painel\ProdutosCategoriasController');
	Route::resource('produtossubcategorias', 'Painel\ProdutosSubcategoriasController');
	Route::resource('produtos', 'Painel\ProdutosController');
	Route::resource('produtosimagens', 'Painel\ProdutosImagensController');
	Route::resource('produtosacabamentos', 'Painel\ProdutosAcabamentosController');
	Route::resource('destaques', 'Painel\DestaquesController');
	Route::resource('espacousuarios', 'Painel\EspacoUsuariosController');
	Route::resource('espacocategorias', 'Painel\EspacoCategoriasController');
	Route::resource('espacoarquivos', 'Painel\EspacoArquivosController');
Route::resource('espacobanner', 'Painel\EspacoBannerController');
//NOVASROTASDOPAINEL//

    Route::get('download', function(){

    	$resultados = Cadastro::orderBy('nome')->select('nome', 'email', 'data', 'ip')
						    					->get()
						    					->toArray();

    	$pathToFile = app_path() . '/internal_files/cadastros_'.date('d-m-Y-H-i-s').'.xls';	    	

    	$titulos = array(
			'nome' => 'Nome',
            'email' => 'E-mail',
            'data' => 'Data de Cadastro',
            'ip' => 'IP de cadastro',
	    );
    	array_unshift($resultados, $titulos);
		Excel::fromArray($resultados)->save($pathToFile);
		return Response::download($pathToFile);
    });
});

laravel/app/controllers/painel/ProdutosImagensController.php
<?php

namespace Painel;

use \Thumb, \View, \Input, \Str, \Session, \File, \Image, \Redirect, \Hash, \Produto, \Categoria, \Subcategoria, \ProdutosImagem;

class ProdutosImagensController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$produtos_id = Input::get('produtos_id');

		if(!$produtos_id)
			return Redirect::back();

		$this->layout->content = View::make('backend.produtosimagens.index')->with('registros', ProdutosImagem::orderBy('ordem', 'ASC')->where('produtos_id', $produtos_id)->get())
																		 	->with('produto', Produto::find($produtos_id));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$produtos_id = Input::get('produtos_id');

		if(!$produtos_id)
			return Redirect::back();

		$this->layout->content = View::make('backend.produtosimagens.form')->with('produto', Produto::find($produtos_id));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new ProdutosImagem;

		$object->produtos_id = Input::get('produtos_id');
		$object->legenda = Input::get('legenda');

		$produto = Produto::find(Input::get('produtos_id'));
		if($produto->categorias_id == 8){
			$t=date('YmdHis');
			$imagem = Thumb::make('imagem', 980, null, 'produtos/', $t);
			Thumb::make('imagem', 180, 180, 'produtos/thumbs/', $t, '#FFFFFF', false);
			if($imagem) $object->imagem = $imagem;
		}else{
			$t=date('YmdHis');
			$imagem = Thumb::make('imagem', 980, null, 'produtos/', $t);
			Thumb::make('imagem', 180, 180, 'produtos/thumbs/', $t, '#FFFFFF', true);
			if($imagem) $object->imagem = $imagem;
		}

		try {

			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Imagem criada com sucesso.');
			return Redirect::route('painel.produtosimagens.index', array('produtos_id' => $object->produtos_id));

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Imagem!'));	

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$produtoImagem = ProdutosImagem::find($id);
		$produto = Produto::find($produtoImagem->produtos_id);
		$this->layout->content = View::make('backend.produtosimagens.edit')->with('registro', $produtoImagem)->with('produto', $produto);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = ProdutosImagem::find($id);
		$object->legenda = Input::get('legenda');

		$produto = Produto::find($object->produtos_id);
		if($produto->categorias_id == 8){
			$t=date('YmdHis');
			$imagem = Thumb::make('imagem', 980, null, 'produtos/', $t);
			Thumb::make('imagem', 180, 180, 'produtos/thumbs/', $t, '#FFFFFF', false);
			if($imagem) $object->imagem = $imagem;
		}else{
			$t=date('YmdHis');
			$imagem = Thumb::make('imagem', 980, null, 'produtos/', $t);
			Thumb::make('imagem', 180, 180, 'produtos/thumbs/', $t, '#FFFFFF', true);
			if($imagem) $object->imagem = $imagem;
		}

		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Imagem alterada com sucesso.');
			return Redirect::route('painel.produtosimagens.index', array('produtos_id' => $object->produtos_id));

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Imagem!'));	

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = ProdutosImagem::find($id);

		$projeto_id = $object->produtos_id;

		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Imagem removida com sucesso.');

		return Redirect::route('painel.produtosimagens.index', array('produtos_id' => $projeto_id));
	}

}

laravel/app/views/backend/produtosimagens/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Imagem
        </h2>  

		{{ Form::open( array('route' => array('painel.produtosimagens.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

				<div class="form-group">
					@if($registro->imagem)
						Imagem Atual<br>
						<img src="assets/images/produtos/thumbs/{{$registro->imagem}}"><br>
						<a href="assets/images/produtos/{{$registro->imagem}}" title="ver tamanho original" target="_blank">ver tamanho original</a><br>
					@endif
					<label for="inputImagem">Trocar Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem">
				</div>				

				<div class="form-group">
					<label for="inputLegenda">Legenda</label>
					<input type="text" class="form-control" id="inputLegenda" name="legenda" value="{{$registro->legenda}}" >
				</div>

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.produtosimagens.index', array('produtos_id' => $registro->produtos_id))}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/produtosimagens/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Imagem
        </h2>  

		<form action="{{URL::route('painel.produtosimagens.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif

				<div class="form-group">
					<label for="inputImagem">Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem" required>
				</div>				<div class="form-group">
					<label for="inputLegenda">Legenda</label>
					<input type="text" class="form-control" id="inputLegenda" name="legenda" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); $s['legenda'] }}" @endif >
				</div>

				<input type="hidden" name="produtos_id" value="{{$produto->id}}">

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.produtosimagens.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/produtosimagens/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Galeria de Imagens do Produto: {{$produto->titulo}} <a href='{{ URL::route('painel.produtosimagens.create', array('produtos_id' => $produto->id)) }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Imagem</a>
    </h2>

    <a href="{{URL::route('painel.produtos.index', array('cat_id' => $produto->categorias_id, 'subcat_id' => $produto->subcategorias_id))}}" title="Voltar" class="btn btn-default">&larr; Voltar</a>

    <table class='table table-striped table-bordered table-hover table-sortable' data-tabela='produtos_imagens'>

        <thead>
            <tr>
                <th>Ordenar</th>
				<th>Imagem</th>
				<th>Legenda</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td class='move-actions'><a href='#' class='btn btn-info btn-move btn-sm'>mover</a></td>
				<td><img src='assets/images/produtos/thumbs/{{ $registro->imagem }}' style='max-width:150px'></td>
				<td>{{ $registro->legenda }}</td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.produtosimagens.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
					{{ Form::open(array('route' => array('painel.produtosimagens.destroy', $registro->id), 'method' => 'delete')) }}
						<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
					{{ Form::close() }}                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop