laravel/app/routes.php
<?php

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('empresa/{slug?}', array('as' => 'empresa', 'uses' => 'EmpresaController@index'));
Route::get('produtos', array('as' => 'produtos', 'uses' => 'ProdutosController@index'));
Route::get('produtos/{categoria}/{produto}', array('as' => 'produtos.detalhes', 'uses' => 'ProdutosController@detalhes'));
Route::get('cases', array('as' => 'cases', 'uses' => 'CasesController@index'));
Route::get('cases/detalhes/{slug}', array('as' => 'cases.detalhes', 'uses' => 'CasesController@detalhes'));
Route::get('clientes', array('as' => 'clientes', 'uses' => 'ClientesController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('contato/enviar', 'ContatoController@enviar');
Route::post('contato/trabalhe', 'ContatoController@trabalhe');

Route::get('espaco-do-arquiteto', array('as' => 'espaco', 'uses' => 'EspacoController@index'));
Route::post('espaco-do-arquiteto', array('as' => 'espaco.login', 'uses' => 'EspacoController@login'));
Route::post('cadastro-do-arquiteto', array('as' => 'espaco.cadastro', 'uses' => 'EspacoController@cadastro'));
Route::get('espaco-do-arquiteto/categoria/{slug}', array('as' => 'espaco.categoria', 'uses' => 'EspacoController@categoria'));
Route::get('espaco-do-arquiteto/logout', array('as' => 'espaco.logout', function(){
	Auth::arquiteto()->logout();
	return Redirect::to('espaco-do-arquiteto');
}));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));


Route::get('download/{arquivo?}', array('before' => 'auth.espaco', function($arquivo){
	
	$pathToFile = app_path() . '/internal_files/'.$arquivo;
	
	if(!$arquivo || !file_exists($pathToFile)){
		App::abort('404');
	}else{
		
		\EspacoUsuario::where('id', '=', Auth::arquiteto()->get()->id)->first()
							   										  ->downloads()
							   										  ->attach(\EspacoArquivo::where('arquivo', '=', $arquivo)->first()->id, array('created_at' => date('Y-m-d H:i:s')));
	
		return Response::download($pathToFile);
	}
}));

Route::get('downloadadmin/{arquivo?}', array('before' => 'painel.auth', function($arquivo){
	
	$pathToFile = app_path() . '/internal_files/'.$arquivo;
	
	if(!$arquivo || !file_exists($pathToFile)){
		App::abort('404');
	}else{
		return Response::download($pathToFile);
	}
}));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'login' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::admin()->attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::admin()->logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));
Route::post('ajax/buscarSubcategorias', array('before' => 'auth', 'uses' => 'Painel\AjaxController@buscarSubcategorias'));
Route::post('ajax/gravarRelAcabamento', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravarRelAcabamento'));
Route::post('ajax/adicionarCadastroNewsletter', 'Painel\AjaxController@adicionarCadastroNewsletter');
Route::get('ajax/buscarAcabamentos/{id_produto}', array('before' => 'auth', 'uses' => 'Painel\AjaxController@buscarAcabamentos'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('texto-da-home', 'Painel\TextoHomeController');
	Route::resource('chamadas', 'Painel\ChamadasController');
	Route::resource('empresa', 'Painel\EmpresaController');
	Route::resource('clientes', 'Painel\ClientesController');
	Route::resource('clientesbanner', 'Painel\ClientesBannerController');	
	Route::resource('contato', 'Painel\ContatoController');
	Route::resource('cases', 'Painel\CasesController');
	Route::resource('casesimagens', 'Painel\CasesImagensController');
	Route::resource('cadastros', 'Painel\CadastrosController', array('only' => array('index', 'destroy')));
	Route::resource('produtoscategorias', 'Painel\ProdutosCategoriasController');
	Route::resource('produtossubcategorias', 'Painel\ProdutosSubcategoriasController');
	Route::resource('produtos', 'Painel\ProdutosController');
	Route::resource('produtosimagens', 'Painel\ProdutosImagensController');
	Route::resource('produtosacabamentos', 'Painel\ProdutosAcabamentosController');
	Route::resource('destaques', 'Painel\DestaquesController');
	Route::resource('espacousuarios', 'Painel\EspacoUsuariosController');
	Route::resource('espacocategorias', 'Painel\EspacoCategoriasController');
	Route::resource('espacoarquivos', 'Painel\EspacoArquivosController');
Route::resource('espacobanner', 'Painel\EspacoBannerController');
//NOVASROTASDOPAINEL//

    Route::get('download', function(){

    	$resultados = Cadastro::orderBy('nome')->select('nome', 'email', 'data', 'ip')
						    					->get()
						    					->toArray();

    	$pathToFile = app_path() . '/internal_files/cadastros_'.date('d-m-Y-H-i-s').'.xls';	    	

    	$titulos = array(
			'nome' => 'Nome',
            'email' => 'E-mail',
            'data' => 'Data de Cadastro',
            'ip' => 'IP de cadastro',
	    );
    	array_unshift($resultados, $titulos);
		Excel::fromArray($resultados)->save($pathToFile);
		return Response::download($pathToFile);
    });
});

laravel/app/models/EspacoUsuario.php
<?php

use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableInterface;

class EspacoUsuario extends Eloquent implements UserInterface, RemindableInterface 
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'espaco_usuarios';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password');

	
	function downloads()
    {
    	return $this->belongsToMany('EspacoArquivo');
    }

	/**
	 * Get the unique identifier for the user.
	 *
	 * @return mixed
	 */
	public function getAuthIdentifier()
	{
		return $this->getKey();
	}

	/**
	 * Get the password for the user.
	 *
	 * @return string
	 */
	public function getAuthPassword()
	{
		return $this->password;
	}

	/**
	 * Get the e-mail address where password reminders are sent.
	 *
	 * @return string
	 */
	public function getReminderEmail()
	{
		return $this->email;
	} 

	/**
	 * Get the token value for the "remember me" session.
	 *
	 * @return string
	 */
	public function getRememberToken()
	{
		return $this->attributes['remember_token'];
	}

	/**
	 * Set the token value for the "remember me" session.
	 *
	 * @param  string  $value
	 * @return void
	 */
	public function setRememberToken($value)
	{
		$this->attributes['remember_token'] = $value;
	}

	/**
	 * Get the column name for the "remember me" token.
	 *
	 * @return string
	 */
	public function getRememberTokenName()
	{
		return 'remember_token';
	}  
}

laravel/app/controllers/painel/EspacoUsuariosController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \EspacoUsuario;

class EspacoUsuariosController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.espacousuarios.index')->with('registros', EspacoUsuario::paginate(25));		
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.espacousuarios.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new EspacoUsuario;

		$object->nome = Input::get('nome');
		$object->login = Input::get('email');
		$object->telefone = Input::get('telefone');
		$object->password = Hash::make(Input::get('senha'));
		
		if(!$object->email || !$object->senha || ($object->senha != Input::get('confirmacao_senha'))){
			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Usuário! Verifique os campos obrigatórios e a confirmação da senha.'));
		}else{
			try {

				$object->save();

				Session::flash('sucesso', true);
				Session::flash('mensagem', 'Usuário criado com sucesso.');
				return Redirect::route('painel.espacousuarios.index');

			} catch (\Exception $e) {

				Session::flash('formulario', Input::all());
				return Redirect::back()->withErrors(array('Erro ao criar Usuário! Email em uso.'));	

			}
		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.espacousuarios.edit')->with('registro', EspacoUsuario::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = EspacoUsuario::find($id);

		$object->nome = Input::get('nome');
		$object->login = Input::get('email');
		$object->telefone = Input::get('telefone');
		$senha = Input::get('senha');
		if($senha)
			$object->password = Hash::make($senha);

		if(!$object->email || ($senha && ($senha != Input::get('confirmacao_senha')))){
			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao alterar Usuário! Verifique os campos obrigatórios e a confirmação da senha.'));
		}else{
			try {

				$object->save();
				Session::flash('sucesso', true);
				Session::flash('mensagem', 'Usuário alterado com sucesso.');
				return Redirect::route('painel.espacousuarios.index');

			} catch (\Exception $e) {

				Session::flash('formulario', Input::all());
				return Redirect::back()->withErrors(array('Erro ao criar Usuário!'));	

			}
		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = EspacoUsuario::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Usuário removido com sucesso.');

		return Redirect::route('painel.espacousuarios.index');
	}

}

laravel/app/views/backend/espacousuarios/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Espaço do Arquiteto - Editar Usuário
        </h2>  

		{{ Form::open( array('route' => array('painel.espacousuarios.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

				<div class="form-group">
					<label for="inputNome">Nome</label>
					<input type="text" class="form-control" id="inputNome" name="nome" value="{{$registro->nome}}" required>
				</div>
				<div class="form-group">
					<label for="inputE-mail">E-mail</label>
					<input type="text" class="form-control" id="inputE-mail" name="email" value="{{$registro->email}}" required>
				</div>
				<div class="form-group">
					<label for="inputTelefone">Telefone</label>
					<input type="text" class="form-control" id="inputTelefone" name="telefone" value="{{$registro->telefone}}">
				</div>
				<div class="form-group">
					<label for="inputSenha">Senha</label>
					<input type="password" class="form-control" id="inputSenha" name="senha">
				</div>
				<div class="form-group">
					<label for="inputConfirmacaoSenha">Confirmação de Senha</label>
					<input type="password" class="form-control" id="inputConfirmacaoSenha" name="confirmacao_senha">
				</div>

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.espacousuarios.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/espacousuarios/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Espaço do Arquiteto - Adicionar Usuário
        </h2>  

		<form action="{{URL::route('painel.espacousuarios.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif

				<div class="form-group">
					<label for="inputNome">Nome</label>
					<input type="text" class="form-control" id="inputNome" name="nome" required>
				</div>
				<div class="form-group">
					<label for="inputE-mail">E-mail</label>
					<input type="text" class="form-control" id="inputE-mail" name="email" required>
				</div>
				<div class="form-group">
					<label for="inputTelefone">Telefone</label>
					<input type="text" class="form-control" id="inputTelefone" name="telefone">
				</div>
				<div class="form-group">
					<label for="inputSenha">Senha</label>
					<input type="password" class="form-control" id="inputSenha" name="senha" required>
				</div>
				<div class="form-group">
					<label for="inputConfirmacaoSenha">Confirmação de Senha</label>
					<input type="password" class="form-control" id="inputConfirmacaoSenha" name="confirmacao_senha" required>
				</div>


				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.espacousuarios.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/espacousuarios/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Espaço do Arquiteto - Usuários <a href='{{ URL::route('painel.espacousuarios.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Usuário</a>
    </h2>

    <table class='table table-striped table-bordered table-hover'>

        <thead>
            <tr>
                <th>Nome</th>
                <th>E-mail</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td>{{ $registro->nome }}</td>
                <td>{{ $registro->email }}</td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.espacousuarios.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
					{{ Form::open(array('route' => array('painel.espacousuarios.destroy', $registro->id), 'method' => 'delete')) }}
						<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
					{{ Form::close() }}                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    {{ $registros->links() }}
</div>

@stop