laravel/app/routes.php
<?php

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('empresa/{slug?}', array('as' => 'empresa', 'uses' => 'EmpresaController@index'));
Route::get('produtos', array('as' => 'produtos', 'uses' => 'ProdutosController@index'));
Route::get('produtos/{categoria}/{produto}', array('as' => 'produtos.detalhes', 'uses' => 'ProdutosController@detalhes'));
Route::get('cases', array('as' => 'cases', 'uses' => 'CasesController@index'));
Route::get('cases/detalhes/{slug}', array('as' => 'cases.detalhes', 'uses' => 'CasesController@detalhes'));
Route::get('clientes', array('as' => 'clientes', 'uses' => 'ClientesController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('contato/enviar', 'ContatoController@enviar');
Route::post('contato/trabalhe', 'ContatoController@trabalhe');

Route::get('espaco-do-arquiteto', array('as' => 'espaco', 'uses' => 'EspacoController@index'));
Route::post('espaco-do-arquiteto', array('as' => 'espaco.login', 'uses' => 'EspacoController@login'));
Route::post('cadastro-do-arquiteto', array('as' => 'espaco.cadastro', 'uses' => 'EspacoController@cadastro'));
Route::get('espaco-do-arquiteto/categoria/{slug}', array('as' => 'espaco.categoria', 'uses' => 'EspacoController@categoria'));
Route::get('espaco-do-arquiteto/logout', array('as' => 'espaco.logout', function(){
	Auth::arquiteto()->logout();
	return Redirect::to('espaco-do-arquiteto');
}));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));


Route::get('download/{arquivo?}', array('before' => 'auth.espaco', function($arquivo){
	
	$pathToFile = app_path() . '/internal_files/'.$arquivo;
	
	if(!$arquivo || !file_exists($pathToFile)){
		App::abort('404');
	}else{
		
		\EspacoUsuario::where('id', '=', Auth::arquiteto()->get()->id)->first()
							   										  ->downloads()
							   										  ->attach(\EspacoArquivo::where('arquivo', '=', $arquivo)->first()->id, array('created_at' => date('Y-m-d H:i:s')));
	
		return Response::download($pathToFile);
	}
}));

Route::get('downloadadmin/{arquivo?}', array('before' => 'painel.auth', function($arquivo){
	
	$pathToFile = app_path() . '/internal_files/'.$arquivo;
	
	if(!$arquivo || !file_exists($pathToFile)){
		App::abort('404');
	}else{
		return Response::download($pathToFile);
	}
}));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'login' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::admin()->attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::admin()->logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));
Route::post('ajax/buscarSubcategorias', array('before' => 'auth', 'uses' => 'Painel\AjaxController@buscarSubcategorias'));
Route::post('ajax/gravarRelAcabamento', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravarRelAcabamento'));
Route::post('ajax/adicionarCadastroNewsletter', 'Painel\AjaxController@adicionarCadastroNewsletter');
Route::get('ajax/buscarAcabamentos/{id_produto}', array('before' => 'auth', 'uses' => 'Painel\AjaxController@buscarAcabamentos'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('texto-da-home', 'Painel\TextoHomeController');
	Route::resource('chamadas', 'Painel\ChamadasController');
	Route::resource('empresa', 'Painel\EmpresaController');
	Route::resource('clientes', 'Painel\ClientesController');
	Route::resource('clientesbanner', 'Painel\ClientesBannerController');	
	Route::resource('contato', 'Painel\ContatoController');
	Route::resource('cases', 'Painel\CasesController');
	Route::resource('casesimagens', 'Painel\CasesImagensController');
	Route::resource('cadastros', 'Painel\CadastrosController', array('only' => array('index', 'destroy')));
	Route::resource('produtoscategorias', 'Painel\ProdutosCategoriasController');
	Route::resource('produtossubcategorias', 'Painel\ProdutosSubcategoriasController');
	Route::resource('produtos', 'Painel\ProdutosController');
	Route::resource('produtosimagens', 'Painel\ProdutosImagensController');
	Route::resource('produtosacabamentos', 'Painel\ProdutosAcabamentosController');
	Route::resource('destaques', 'Painel\DestaquesController');
	Route::resource('espacousuarios', 'Painel\EspacoUsuariosController');
	Route::resource('espacocategorias', 'Painel\EspacoCategoriasController');
	Route::resource('espacoarquivos', 'Painel\EspacoArquivosController');
Route::resource('espacobanner', 'Painel\EspacoBannerController');
//NOVASROTASDOPAINEL//

    Route::get('download', function(){

    	$resultados = Cadastro::orderBy('nome')->select('nome', 'email', 'data', 'ip')
						    					->get()
						    					->toArray();

    	$pathToFile = app_path() . '/internal_files/cadastros_'.date('d-m-Y-H-i-s').'.xls';	    	

    	$titulos = array(
			'nome' => 'Nome',
            'email' => 'E-mail',
            'data' => 'Data de Cadastro',
            'ip' => 'IP de cadastro',
	    );
    	array_unshift($resultados, $titulos);
		Excel::fromArray($resultados)->save($pathToFile);
		return Response::download($pathToFile);
    });
});

laravel/app/models/Produto.php
<?php

class Produto extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'produtos';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

    public function categoria(){
    	return $this->belongsTo('Categoria', 'categorias_id');
    }

    public function imagens(){
    	return $this->hasMany('ProdutosImagem', 'produtos_id')->orderBy('ordem', 'ASC');
    }

	public function acabamentos() {
        return $this->belongsToMany('Acabamento');
    }
}

laravel/app/controllers/ProdutosController.php
<?php

use \Categoria, \Subcategoria, \Produto, \ProdutosImagens, \Acabamento, \Destaque;

class ProdutosController extends BaseController {

	protected $layout = 'frontend.templates.index';

	public function index()
	{
		$destaques = Destaque::orderBy('ordem', 'ASC')->get();
		
		foreach ($destaques as $key => $value) {
			$produto = Produto::find($value->id_produto);
			
			$cat = Categoria::find($produto->categorias_id);

			$value->link = "produtos/".$cat->slug.'/'.$produto->slug;
			$value->titulo = $produto->titulo;
		}

		$this->layout->content = View::make('frontend.produtos.index')->with('menu', Categoria::orderBy('ordem', 'asc')->get())
																	  ->with('destaques', $destaques);
	}

	public function detalhes($categoria, $produto){

		$this->layout->with('css', 'css/produtos');

		$categoria = Categoria::where('slug', '=', $categoria)->first();
		
		if(is_null($categoria))
			App::abort('404');

		$produto = Produto::where('slug', '=', $produto)->where('categorias_id', $categoria->id)
														->first();
		
		if(is_null($produto))
		 	App::abort('404');

		$this->layout->content = View::make('frontend.produtos.detalhes')->with('menu', Categoria::orderBy('ordem', 'asc')->get())
																	  	 ->with('produto', $produto);	
	}
}

laravel/app/controllers/painel/ProdutosController.php
<?php

namespace Painel;

use \Thumb, \View, \Input, \Str, \Session, \File, \Image, \Redirect, \Hash, \Categoria, \Subcategoria, \Produto, \Destaque;

class ProdutosController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$listaCategorias = Categoria::orderBy('ordem', 'ASC')->get();
		$listaSubcategorias = null;

		if(Input::has('cat_id')){
			$selecCategorias = Categoria::find(Input::get('cat_id'));
			$listaSubcategorias = Subcategoria::orderBy('ordem', 'ASC')->where('categorias_id', $selecCategorias->id)->get();
		}else{
			$selecCategorias = null;
		}

		if(!is_null($selecCategorias)){
			$produtos = Produto::orderBy('ordem', 'ASC')->where('categorias_id', $selecCategorias->id)->get();
		}else{
			$produtos = Produto::orderBy('ordem', 'ASC')->get();
		}

		$this->layout->content = View::make('backend.produtos.index')->with('registros', $produtos)
																	 ->with('listaCategorias', $listaCategorias)
																	 ->with('selecCategorias', $selecCategorias);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$listaCategorias = Categoria::orderBy('ordem', 'ASC')->get();
		$this->layout->content = View::make('backend.produtos.form')->with('listaCategorias', $listaCategorias);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Produto;

		$object->titulo = Input::get('titulo');
		$object->texto = Input::get('texto');
		$object->categorias_id = Input::get('categorias_id');
		$object->subcategorias_id = 0;

		$imagem = Thumb::make('imagem', 760, 220, 'produtos/');
		if($imagem) $object->imagem = $imagem;
		
		$imagem_dimensoes = Thumb::make('imagem_dimensoes', 760, null, 'produtos/');
		if($imagem_dimensoes) $object->imagem_dimensoes = $imagem_dimensoes;	

		try {

			$object->save();

			$object->slug = Str::slug($object->id.'-'.$object->titulo);
			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Produto criado com sucesso.');
			return Redirect::route('painel.produtos.index', array('cat_id' => $object->categorias_id, 'subcat_id' => $object->subcategorias_id));

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Produto!'));	

		}		
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$produto = Produto::find($id);
		$listaCategorias = Categoria::orderBy('ordem', 'ASC')->get();
		$this->layout->content = View::make('backend.produtos.edit')->with('registro', $produto)
																	->with('listaCategorias', $listaCategorias);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Produto::find($id);

		$object->titulo = Input::get('titulo');
		$object->texto = Input::get('texto');
		$object->categorias_id = Input::get('categorias_id');
		$object->subcategorias_id = 0;

		$imagem = Thumb::make('imagem', 760, 220, 'produtos/');
		if($imagem) $object->imagem = $imagem;
		
		$imagem_dimensoes = Thumb::make('imagem_dimensoes', 760, null, 'produtos/');
		if($imagem_dimensoes) $object->imagem_dimensoes = $imagem_dimensoes;

		try {

			$object->save();
			$object->slug = Str::slug($object->id.'-'.$object->titulo);
			$object->save();
			
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Produto alterado com sucesso.');
			return Redirect::route('painel.produtos.index', array('cat_id' => $object->categorias_id, 'subcat_id' => $object->subcategorias_id));

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Produto!'));	

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Produto::find($id);

		$cat_id = $object->categorias_id;
		$subcat_id = $object->subcategorias_id;

		$object->delete();

		Destaque::where('id_produto', '=', $id)->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Produto removido com sucesso.');

		return Redirect::route('painel.produtos.index', array('cat_id' => $cat_id, 'subcat_id' => $subcat_id));
	}

}

laravel/app/views/backend/produtos/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Linha
        </h2>  

		{{ Form::open( array('route' => array('painel.produtos.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif

		    	<div class="form-group">
					<label for="inputCategoria">Categoria</label>
					<select name="categorias_id" class="form-control" id="inputCategoria" required>
						<option value=""></option>
				    	@if(sizeof($listaCategorias))
							@foreach($listaCategorias as $k => $v)
								<option value="{{$v->id}}" @if($registro->categorias_id == $v->id) selected @endif>{{$v->titulo}}</option>
							@endforeach
				    	@endif
					</select>
				</div>

				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" value="{{$registro->titulo}}" required>
				</div>				

				<div class="form-group">
					@if($registro->imagem)
						Imagem Atual<br>
						<img src="assets/images/produtos/{{$registro->imagem}}"><br>
					@endif
					<label for="inputImagem">Trocar Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem">
				</div>				

				<div class="form-group">
					<label for="inputTexto">Texto</label>
					<textarea name="texto" class="form-control" id="inputTexto" >{{$registro->texto }}</textarea>
				</div>				

				<div class="form-group">
					@if($registro->imagem_dimensoes)
						Dimensões<br>
						<img src="assets/images/produtos/{{$registro->imagem_dimensoes}}"><br>
					@endif
					<label for="inputDimensões">Alterar imagem ilustrativa das Dimensões</label>
					<input type="file" class="form-control" id="inputDimensões" name="imagem_dimensoes">
				</div>

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.produtos.index', array('cat_id' => $registro->categorias_id, 'subcat_id' => $registro->subcategorias_id))}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/produtos/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Linha
        </h2>  

		<form action="{{URL::route('painel.produtos.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif
				
				<div class="form-group">
					<label for="inputCategoria">Categoria</label>
					<select name="categorias_id" class="form-control" id="inputCategoria" required>
						<option value=""></option>
				    	@if(sizeof($listaCategorias))
							@foreach($listaCategorias as $k => $v)
								<option value="{{$v->id}}">{{$v->titulo}}</option>
							@endforeach
				    	@endif
					</select>
				</div>

				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); $s['titulo'] }}" @endif required>
				</div>				

				<div class="form-group">
					<label for="inputImagem">Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem" required>
				</div>				

				<div class="form-group">
					<label for="inputTexto">Texto</label>
					<textarea name="texto" class="form-control" id="inputTexto">@if(Session::has('formulario')) {{ $s=Session::get('formulario'); $s['texto'] }} @endif</textarea>
				</div>					

				<div class="form-group">
					<label for="inputDimensões">Dimensões (imagem ilustrativa)</label>
					<input type="file" class="form-control" id="inputDimensões" name="imagem_dimensoes">
				</div>

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.produtos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/produtos/index.blade.php
@section('conteudo')

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Linhas <a href='{{ URL::route('painel.produtos.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Produto</a>
    </h2>

    @if(sizeof($listaCategorias))
        Categorias:
        <div class="btn-group">
            @foreach ($listaCategorias as $key => $value)
                <a href="{{URL::route('painel.produtos.index', array('cat_id' => $value->id))}}" title="Filtrar por categoria : {{$value->titulo}}" class="btn btn-default @if(!is_null($selecCategorias) && $selecCategorias->id==$value->id) btn-info @endif">{{$value->titulo}}</a>
            @endforeach
        </div>
    @endif
    
    <br><br>

    @if(!is_null($selecCategorias))

        <table class='table table-striped table-bordered table-hover table-sortable' data-tabela='produtos'>

            <thead>
                <tr>
                    <th>Ordenar</th>
    				<th>Título</th>
    				<th>Imagem</th>
    				<th>Texto</th>
                    <th>Acabamentos</th>
                    <th>Galeria de Imagens</th>
                    <th><span class="glyphicon glyphicon-cog"></span></th>
                </tr>
            </thead>

            <tbody>
                @if($registros)
                    @foreach ($registros as $registro)

                        <tr class="tr-row" id="row_{{ $registro->id }}">
                            <td class='move-actions'><a href='#' class='btn btn-info btn-move btn-sm'>mover</a></td>
                            <td>{{ $registro->titulo }}</td>
            				<td><img src='assets/images/produtos/{{ $registro->imagem }}' style='max-width:150px'></td>
            				<td>{{ Str::words(strip_tags($registro->texto), 15) }}</td>
                            <td><button class="btn btn-sm btn-default abreAcabamentos" data-prod="{{$registro->id}}" data-toggle="modal" data-target="#myModal" title="Gerenciar Acabamentos do Produto {{$registro->titulo}}">gerenciar</button></td>
                            <td><a href="{{ URL::route('painel.produtosimagens.index', array('produtos_id' => $registro->id)) }}" class="btn btn-sm btn-default" title="Gerenciar Galeria de Fotos do Produto {{$registro->titulo}}">gerenciar</a></td>
                            <td class="crud-actions">
                                <a href='{{ URL::route('painel.produtos.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
        						{{ Form::open(array('route' => array('painel.produtos.destroy', $registro->id), 'method' => 'delete')) }}
        							<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
        						{{ Form::close() }}                    
                            </td>
                        </tr>

                    @endforeach
                @else
                    <tr><td colspan="5"></td></tr>
                @endif
            </tbody>

        </table>
    
    @else 
        
        <h2 style="text-align:center;">Selecione uma categoria</h2>

    @endif
    
</div>

@stop